---

- name: Create log directory
  file:
    state=directory
    dest="{{celery_logdir}}"
    owner="{{celery_user}}"
    group="{{celery_group}}"
    mode='0755'

- name: Create run directory
  file:
    state=directory
    dest="{{celery_piddir}}"
    owner="{{celery_user}}"
    group="{{celery_group}}"
    mode='0755'

- name: Configure Celery
  template: src=celery.conf.j2 dest=/etc/default/celeryd
#  notify:
#    - Restart Celery

- name: Configure Celery Service Scripts
  template: src=celery.service.j2 dest=/etc/init.d/celeryd

- name: Ensure celery 
  file: path=/etc/init.d/celeryd mode=0755

- name: Configure Celery log rotation
  template: src=logrotate_celery.j2 dest=/etc/logrotate.d/celery
